"""
Comprehensive character creation data for NEXUS RPG.
All origins, formative years, and specializations with full descriptions,
attribute/skill modifiers, starting credits, equipment, etc.
"""

ORIGINS = [
    # ═══ ЗЕМНЫЕ ═══
    {
        "id": "ORIGIN_EARTH_ELITE", "name": "Наследник Земной Элиты", "rarity": "редкое",
        "group": "Земля",
        "description": "Родились в элитном анклаве Земли, окружённые приватной охраной и лучшими технологиями. Высокое образование, дипломатические связи, но оторванность от реальной жизни.",
        "attr_mods": {"charisma": 1, "intelligence": 1, "endurance": -1},
        "skill_mods": {"education": 2, "diplomacy": 1, "survival": -1},
        "credits": 100000, "influence": 10,
    },
    {
        "id": "ORIGIN_EARTH_SLUMS", "name": "Дитя Трущоб", "rarity": "обычное",
        "group": "Земля",
        "description": "Выжили в нижних уровнях города, где неон гасится пылью и страхом. Закалены жизнью на улицах, но образование минимальное.",
        "attr_mods": {"endurance": 2, "dexterity": 1, "intelligence": -1},
        "skill_mods": {"survival": 2, "stealth": 1, "education": -1},
        "credits": 1000,
    },
    {
        "id": "ORIGIN_EARTH_CORP_HEIR", "name": "Корпоративный Наследник", "rarity": "редкое",
        "group": "Земля",
        "description": "Семья владеет акциями крупных корпораций. Престиж, власть и огромная ответственность. Вы привыкли к роскоши и интригам.",
        "attr_mods": {"charisma": 2},
        "skill_mods": {"negotiation": 2, "bureaucracy": 1},
        "credits": 250000, "influence": 15,
    },
    {
        "id": "ORIGIN_EARTH_JOURNALIST", "name": "Журналист-Расследователь", "rarity": "необычное",
        "group": "Земля",
        "description": "Родители — известные журналисты. Научились искать правду в мире корпоративной лжи. У вас есть контакты в самых неожиданных местах.",
        "attr_mods": {"intelligence": 1},
        "skill_mods": {"education": 2, "negotiation": 1, "stealth": 1},
        "credits": 35000,
    },
    {
        "id": "ORIGIN_EARTH_MILITARY", "name": "Военный Отпрыск", "rarity": "обычное",
        "group": "Земля",
        "description": "Выросли на военных базах Земли, окружённые дисциплиной и тренировками. Военная жизнь — единственное, что вы знаете.",
        "attr_mods": {"strength": 1, "willpower": 1},
        "skill_mods": {"combat": 1, "survival": 1},
        "credits": 45000,
    },
    {
        "id": "ORIGIN_EARTH_DIPLOMAT", "name": "Дипломат Земли", "rarity": "необычное",
        "group": "Земля",
        "description": "Представитель Объединённого Правительства Земли в межпланетных отношениях. Мастер переговоров и политических интриг.",
        "attr_mods": {"charisma": 2, "intelligence": 1},
        "skill_mods": {"diplomacy": 2, "law": 1, "bureaucracy": 1},
        "credits": 80000, "influence": 8,
    },
    {
        "id": "ORIGIN_EARTH_HACKER", "name": "Хакер-Активист Земли", "rarity": "необычное",
        "group": "Земля",
        "description": "Член подпольной группы кибер-активистов, борющихся с корпоративным контролем. Виртуозное владение кодом — ваш главный козырь.",
        "attr_mods": {"intelligence": 2, "endurance": -1},
        "skill_mods": {"hacking": 3, "technology": 1, "criminal": 1},
        "credits": 15000,
    },
    {
        "id": "ORIGIN_EARTH_REFUGEE", "name": "Беженец из Лагеря", "rarity": "обычное",
        "group": "Земля",
        "description": "Пережили худшее, что может предложить человечество. Климатические катастрофы отняли дом, но не сломили дух.",
        "attr_mods": {"willpower": 2, "endurance": 1},
        "skill_mods": {"survival": 3, "stealth": 1},
        "credits": 500,
    },
    # ═══ МАРС ═══
    {
        "id": "ORIGIN_MARS_MILITARY", "name": "Потомок Марсианских Солдат", "rarity": "обычное",
        "group": "Марс",
        "description": "Привыкли к дисциплине и симуляциям боевых учений в республиканской академии. Марсианская военная школа закалила ваш характер.",
        "attr_mods": {"strength": 1, "endurance": 1, "willpower": 1},
        "skill_mods": {"combat": 1, "piloting": 1},
        "credits": 35000, "influence": 5,
    },
    {
        "id": "ORIGIN_MARS_SCIENTIST", "name": "Учёный Марса", "rarity": "необычное",
        "group": "Марс",
        "description": "Родились среди терраформеров и исследователей. Для вас наука — это всё. Лаборатория была вашей детской площадкой.",
        "attr_mods": {"intelligence": 2, "tech_empathy": 1, "charisma": -1},
        "skill_mods": {"technology": 2, "engineering": 1},
        "credits": 50000, "influence": 3,
    },
    {
        "id": "ORIGIN_MARS_REBEL", "name": "Марсианский Повстанец", "rarity": "редкое",
        "group": "Марс",
        "description": "Семья участвовала в борьбе за независимость Марса от Земли. Вы выросли с оружием в руках и идеалами свободы в сердце.",
        "attr_mods": {"willpower": 1, "endurance": 1},
        "skill_mods": {"combat": 2, "stealth": 2, "survival": 1},
        "credits": 8000,
    },
    {
        "id": "ORIGIN_MARS_ENGINEER", "name": "Марсианский Инженер-Терраформер", "rarity": "необычное",
        "group": "Марс",
        "description": "Родители работали над преобразованием атмосферы Марса. Инженерная мысль течёт в ваших венах.",
        "attr_mods": {"intelligence": 1, "tech_empathy": 1},
        "skill_mods": {"engineering": 3, "technology": 1, "survival": 1},
        "credits": 55000,
    },
    {
        "id": "ORIGIN_MARS_TUNNELER", "name": "Марсианский Туннельный Крыс", "rarity": "обычное",
        "group": "Марс",
        "description": "Выросли в подземных городах, научились выживать в замкнутых пространствах. Знаете каждый коридор и вентиляцию.",
        "attr_mods": {"dexterity": 1, "endurance": 1},
        "skill_mods": {"survival": 2, "stealth": 2, "engineering": 1},
        "credits": 5000,
    },
    # ═══ ПОЯС АСТЕРОИДОВ ═══
    {
        "id": "ORIGIN_BELT_SMUGGLER", "name": "Потомок Контрабандистов Пояса", "rarity": "необычное",
        "group": "Пояс астероидов",
        "description": "Семья жила тайной торговлей во Внешней системе. Вы научились летать раньше, чем ходить.",
        "attr_mods": {"reflexes": 2, "dexterity": 1},
        "skill_mods": {"piloting": 2, "criminal": 2},
        "credits": 25000,
    },
    {
        "id": "ORIGIN_BELT_MINER", "name": "Шахтёр с Цереры", "rarity": "обычное",
        "group": "Пояс астероидов",
        "description": "Добывали руду в недрах астероида, починив всё подручными средствами. Тяжёлый труд сделал вас крепким и находчивым.",
        "attr_mods": {"strength": 2, "endurance": 1},
        "skill_mods": {"engineering": 1, "survival": 1},
        "credits": 12000,
    },
    {
        "id": "ORIGIN_BELT_SALVAGER", "name": "Космический Утилизатор", "rarity": "необычное",
        "group": "Пояс астероидов",
        "description": "Специализировались на утилизации обломков кораблей и станций. Каждый выход в открытый космос мог стать последним.",
        "attr_mods": {"tech_empathy": 1, "reflexes": 1},
        "skill_mods": {"piloting": 2, "technology": 2, "engineering": 1},
        "credits": 18000,
    },
    {
        "id": "ORIGIN_BELT_NOMAD", "name": "Кочевник-Шахтер", "rarity": "обычное",
        "group": "Пояс астероидов",
        "description": "Кочующие шахтёрские корабли — весь ваш мир. Знаете навигацию по звёздам и как экономить каждый литр кислорода.",
        "attr_mods": {"endurance": 1, "willpower": 1},
        "skill_mods": {"piloting": 1, "survival": 2, "engineering": 1},
        "credits": 8000,
    },
    {
        "id": "ORIGIN_BELT_TRADER", "name": "Семья Межзвёздных Торговцев", "rarity": "необычное",
        "group": "Пояс астероидов",
        "description": "Торговые рейсы к дальним колониям. Вы знаете цену каждому товару и умеете торговаться с любым существом.",
        "attr_mods": {"charisma": 1, "intelligence": 1},
        "skill_mods": {"negotiation": 2, "piloting": 1, "diplomacy": 1},
        "credits": 60000,
    },
    # ═══ ВНЕШНЯЯ СИСТЕМА ═══
    {
        "id": "ORIGIN_OUTER_EUROPA", "name": "Глубоководный Исследователь Европы", "rarity": "редкое",
        "group": "Внешняя система",
        "description": "Выросли на спутнике Юпитера, исследуя подлёдный океан. Подводные базы и океанические экспедиции — ваша стихия.",
        "attr_mods": {"intelligence": 1, "willpower": 1, "endurance": -1},
        "skill_mods": {"biology": 2, "technology": 1, "survival": 1},
        "credits": 40000,
    },
    {
        "id": "ORIGIN_OUTER_TITAN", "name": "Метановый Фермер Титана", "rarity": "необычное",
        "group": "Внешняя система",
        "description": "Родители добывали метан в атмосфере Титана для топлива. Суровые условия воспитали стойкость и изобретательность.",
        "attr_mods": {"endurance": 2},
        "skill_mods": {"piloting": 2, "engineering": 1, "survival": 1},
        "credits": 32000,
    },
    {
        "id": "ORIGIN_OUTER_GANYMEDE", "name": "Исследователь Ганимеда", "rarity": "редкое",
        "group": "Внешняя система",
        "description": "Изучали биохимию в подледных лабораториях. Самая передовая научная колония человечества стала вашим домом.",
        "attr_mods": {"intelligence": 3, "tech_empathy": 1, "endurance": -1},
        "skill_mods": {"medicine": 1, "technology": 2, "biology": 1},
        "credits": 80000, "influence": 5,
    },
    {
        "id": "ORIGIN_OUTER_VESTA", "name": "Военная База Весты", "rarity": "необычное",
        "group": "Внешняя система",
        "description": "Секретная подготовка элиты на Весте. Вас тренировали быть лучшими — или быть мёртвыми.",
        "attr_mods": {"strength": 1, "reflexes": 2, "charisma": -1},
        "skill_mods": {"combat": 2, "stealth": 1, "piloting": 1},
        "credits": 30000,
    },
    # ═══ УНИКАЛЬНЫЕ ═══
    {
        "id": "ORIGIN_UNIQUE_MAGNATE", "name": "Технологический Магнат", "rarity": "легендарное",
        "group": "Уникальные",
        "description": "Молодой миллиардер, создавший революционную технологию. Ваше имя знают на каждой станции системы. Но изоляция в мире богатства оставила пробелы в уличных навыках.",
        "attr_mods": {"intelligence": 1, "charisma": 1, "endurance": -1},
        "skill_mods": {"technology": 2, "negotiation": 1, "bureaucracy": 1},
        "credits": 500000, "influence": 30,
    },
    {
        "id": "ORIGIN_UNIQUE_NOMAD", "name": "Ребёнок Космических Кочевников", "rarity": "редкое",
        "group": "Уникальные",
        "description": "Родились на борту торгового корабля, странствующего по системе. Космос — ваш единственный дом.",
        "attr_mods": {"dexterity": 1, "reflexes": 1},
        "skill_mods": {"piloting": 2, "negotiation": 1, "survival": 1},
        "credits": 28000,
    },
    {
        "id": "ORIGIN_UNIQUE_EXPERIMENT", "name": "Корпоративный Эксперимент", "rarity": "легендарное",
        "group": "Уникальные",
        "description": "Вы — продукт секретной корпоративной программы. Генетические модификации дали силу, но забрали часть человечности.",
        "attr_mods": {"strength": 2, "reflexes": 2, "endurance": 1, "charisma": -2},
        "skill_mods": {"combat": 2, "technology": 1},
        "credits": 5000,
    },
    {
        "id": "ORIGIN_UNIQUE_AI_CHILD", "name": "Воспитанник ИИ", "rarity": "легендарное",
        "group": "Уникальные",
        "description": "Ребёнок-сирота, которого вырастил автономный ИИ заброшенной космической станции. Ваше понимание машин — на грани сверхъестественного.",
        "attr_mods": {"intelligence": 2, "tech_empathy": 3, "charisma": -2},
        "skill_mods": {"hacking": 2, "technology": 2, "engineering": 1},
        "credits": 10000,
    },
]


FORMATIVE_YEARS = [
    # ═══ ВОЕННЫЕ / БОЕВЫЕ ═══
    {
        "id": "FY_MARS_ACADEMY", "name": "Военная Академия Марса",
        "group": "Военные",
        "description": "Четыре года жёсткой муштры, тактических симуляций и боевых учений. Вы научились стрелять, командовать и выживать.",
        "attr_mods": {"strength": 1, "willpower": 1},
        "skill_mods": {"combat": 2, "technology": 1},
    },
    {
        "id": "FY_SLUMS_GANGWAR", "name": "Война банд в трущобах",
        "group": "Криминальные",
        "description": "Территориальные войны научили вас драться не по правилам. Шрамы — как карта вашей юности.",
        "attr_mods": {"endurance": 1},
        "skill_mods": {"combat": 2, "stealth": 1, "criminal": 1},
    },
    {
        "id": "FY_MILITARY_VOLUNTEER", "name": "Добровольная военная подготовка",
        "group": "Военные",
        "description": "Записались добровольцем в планетарную милицию. Дисциплина и товарищество стали вашей второй натурой.",
        "attr_mods": {"willpower": 1},
        "skill_mods": {"combat": 1, "survival": 1, "diplomacy": 1},
    },
    # ═══ КОРПОРАТИВНЫЕ ═══
    {
        "id": "FY_CORP_INTERNSHIP", "name": "Корпоративная стажировка",
        "group": "Корпоративные",
        "description": "Стажировка в мегакорпорации открыла глаза на мир корпоративных интриг. Вы научились составлять отчёты, вести переговоры и лавировать между боссами.",
        "attr_mods": {"intelligence": 1},
        "skill_mods": {"bureaucracy": 2, "negotiation": 1},
    },
    {
        "id": "FY_CORP_ESPIONAGE", "name": "Свидетель корпоративного шпионажа",
        "group": "Корпоративные",
        "description": "Случайно стали свидетелем промышленного шпионажа. Это научило вас быть осторожным и замечать ложь.",
        "attr_mods": {"intelligence": 1},
        "skill_mods": {"stealth": 1, "hacking": 1, "education": 1},
    },
    {
        "id": "FY_FAMILY_BUSINESS", "name": "Наследование семейного бизнеса",
        "group": "Корпоративные",
        "description": "В юном возрасте взяли на себя управление семейным делом. Ранняя ответственность закалила характер и обострила деловую хватку.",
        "attr_mods": {"charisma": 1},
        "skill_mods": {"negotiation": 2, "bureaucracy": 1},
    },
    # ═══ АКАДЕМИЧЕСКИЕ ═══
    {
        "id": "FY_GIFTED_PROGRAM", "name": "Программа для одарённых детей",
        "group": "Академические",
        "description": "Ваш IQ открыл двери в элитную академию. Ускоренное обучение, научные олимпиады и первые патенты ещё до совершеннолетия.",
        "attr_mods": {"intelligence": 2},
        "skill_mods": {"education": 2, "technology": 1},
    },
    {
        "id": "FY_SCIENTIFIC_DISCOVERY", "name": "Участие в научном открытии",
        "group": "Академические",
        "description": "Помогали исследовательской группе и стали соавтором важного открытия. Мир науки распахнул перед вами двери.",
        "attr_mods": {"intelligence": 1},
        "skill_mods": {"biology": 1, "technology": 1, "education": 1},
    },
    {
        "id": "FY_YOUNG_HACKER", "name": "Признание как юный хакер",
        "group": "Технологические",
        "description": "В 14 лет взломали корпоративную базу данных. Арест, условный срок — и репутация в хакерском подполье.",
        "attr_mods": {"intelligence": 1},
        "skill_mods": {"hacking": 2, "technology": 1, "criminal": 1},
    },
    # ═══ КРИМИНАЛЬНЫЕ ═══
    {
        "id": "FY_STREET_LIFE", "name": "Жизнь на улице",
        "group": "Криминальные",
        "description": "Беспризорная юность научила воровать, прятаться и не доверять никому. Улица была жестоким, но эффективным учителем.",
        "attr_mods": {"dexterity": 1, "endurance": 1},
        "skill_mods": {"stealth": 2, "criminal": 1, "survival": 1},
    },
    {
        "id": "FY_SMUGGLING_RUNS", "name": "Контрабандные рейсы",
        "group": "Криминальные",
        "description": "Подрабатывали курьером для контрабандистов Пояса. Научились летать быстро и не задавать вопросов.",
        "attr_mods": {"reflexes": 1},
        "skill_mods": {"piloting": 2, "criminal": 1},
    },
    # ═══ КАТАСТРОФЫ ═══
    {
        "id": "FY_COSMIC_CATASTROPHE", "name": "Пережили космическую катастрофу",
        "group": "Катастрофы",
        "description": "Разгерметизация станции, взрыв реактора или столкновение с астероидом — вы выжили, когда другие погибли. Это оставило шрамы, но закалило.",
        "attr_mods": {"willpower": 2, "endurance": 1},
        "skill_mods": {"survival": 2, "medicine": 1},
    },
    {
        "id": "FY_FAMILY_BANKRUPTCY", "name": "Банкротство семьи",
        "group": "Катастрофы",
        "description": "Из роскоши — в нищету за одну ночь. Крах семейного бизнеса научил ценить каждый кредит и не доверять внешнему блеску.",
        "attr_mods": {"willpower": 1},
        "skill_mods": {"survival": 1, "negotiation": 1, "criminal": 1},
    },
    # ═══ СОЦИАЛЬНЫЕ ═══
    {
        "id": "FY_DIPLOMATIC_MISSION", "name": "Участие в дипломатической миссии",
        "group": "Социальные",
        "description": "Сопровождали родителей или наставника в дипломатической миссии. Научились понимать политику и видеть за словами скрытые мотивы.",
        "attr_mods": {"charisma": 1},
        "skill_mods": {"diplomacy": 2, "law": 1},
    },
    {
        "id": "FY_SPORTS_ACHIEVEMENTS", "name": "Спортивные достижения",
        "group": "Социальные",
        "description": "Чемпион колонии по гравитационному боксу или нулевому-G акробатике. Тело — ваш главный инструмент.",
        "attr_mods": {"strength": 1, "dexterity": 1, "endurance": 1},
        "skill_mods": {"combat": 1},
    },
    {
        "id": "FY_ARTISTIC_TALENT", "name": "Признание художественного таланта",
        "group": "Социальные",
        "description": "Ваши работы выставлялись в галереях от Земли до Ганимеда. Творчество научило видеть красоту и манипулировать эмоциями.",
        "attr_mods": {"charisma": 2},
        "skill_mods": {"diplomacy": 1, "negotiation": 1},
    },
    # ═══ ТЕХНОЛОГИЧЕСКИЕ ═══
    {
        "id": "FY_ROBOT_BUILDER", "name": "Собирали роботов с детства",
        "group": "Технологические",
        "description": "Первого дрона собрали в 10 лет из деталей мусорника. К 18 у вас была мастерская и десяток патентов.",
        "attr_mods": {"tech_empathy": 2},
        "skill_mods": {"engineering": 2, "technology": 1},
    },
    {
        "id": "FY_CYBERNETIC_IMPLANT", "name": "Ранняя кибернетическая модификация",
        "group": "Технологические",
        "description": "Первый имплант поставили в 15 — нейроинтерфейс для ускоренного обучения. Побочные эффекты: мигрени и ощущение чужеродности.",
        "attr_mods": {"intelligence": 1, "tech_empathy": 1},
        "skill_mods": {"hacking": 1, "technology": 1},
    },
    # ═══ МЕДИЦИНСКИЕ ═══
    {
        "id": "FY_PLAGUE_SURVIVOR", "name": "Пережили космическую чуму",
        "group": "Катастрофы",
        "description": "Эпидемия на станции. Вы помогали медикам и видели смерть вблизи. После выздоровления решили, что жизнь слишком коротка для страха.",
        "attr_mods": {"willpower": 1, "endurance": 1},
        "skill_mods": {"medicine": 2, "biology": 1},
    },
    {
        "id": "FY_MEDICAL_APPRENTICE", "name": "Ученик полевого медика",
        "group": "Медицинские",
        "description": "Подрабатывали ассистентом хирурга в трущобных клиниках. Научились зашивать раны и ставить капельницы в полевых условиях.",
        "attr_mods": {"intelligence": 1},
        "skill_mods": {"medicine": 2, "biology": 1},
    },
    # ═══ КОСМИЧЕСКИЕ ═══
    {
        "id": "FY_FIRST_SPACEFLIGHT", "name": "Первый одиночный полёт",
        "group": "Космические",
        "description": "В 16 лет угнали отцовский шаттл и слетали до ближайшей станции. Нагоняй был страшный, но с тех пор космос — ваша стихия.",
        "attr_mods": {"reflexes": 1, "dexterity": 1},
        "skill_mods": {"piloting": 2, "engineering": 1},
    },
    {
        "id": "FY_ALIEN_ARTIFACT", "name": "Нашли инопланетный артефакт",
        "group": "Космические",
        "description": "На заброшенном астероиде обнаружили объект нечеловеческого происхождения. С тех пор вас преследуют странные сны и ощущение чужого присутствия.",
        "attr_mods": {"intelligence": 1, "willpower": 1},
        "skill_mods": {"technology": 1, "education": 1, "biology": 1},
    },
    {
        "id": "FY_LOVE_TRIANGLE", "name": "Любовный треугольник",
        "group": "Социальные",
        "description": "Бурный роман, предательство и разбитое сердце. Эмоциональные шрамы научили разбираться в людях и защищать своё сердце.",
        "attr_mods": {"charisma": 1},
        "skill_mods": {"negotiation": 1, "stealth": 1},
    },
    # ═══ ДОПОЛНИТЕЛЬНЫЕ ═══
    {
        "id": "FY_UNDERGROUND_FIGHTS", "name": "Подпольные бои",
        "group": "Криминальные",
        "description": "С 14 лет дрались на подпольных рингах в нижних уровнях. Шрамы, сломанный нос и навсегда перебитые костяшки — но зато научились выживать.",
        "attr_mods": {"endurance": 1, "strength": 1},
        "skill_mods": {"combat": 2, "survival": 1},
    },
    {
        "id": "FY_MERCHANT_FLEET", "name": "Каюта на торговом корабле",
        "group": "Космические",
        "description": "Выросли на борту торгового судна, курсирующего между станциями Пояса. Научились торговаться, чинить трубы и спать при нулевой гравитации.",
        "attr_mods": {"dexterity": 1},
        "skill_mods": {"piloting": 1, "engineering": 1, "negotiation": 1},
    },
    {
        "id": "FY_ORPHANAGE_AI", "name": "Воспитание в приюте ИИ",
        "group": "Технологические",
        "description": "Автоматизированный приют, где единственными «родителями» были обучающие программы. Гениальная база знаний, но пробелы в человеческих эмоциях.",
        "attr_mods": {"intelligence": 2},
        "skill_mods": {"technology": 1, "education": 1},
    },
    {
        "id": "FY_MINING_ACCIDENT", "name": "Авария на шахте",
        "group": "Катастрофы",
        "description": "Обвал в марсианской шахте — неделя в темноте, рацион на троих, кислород на двоих. Выжили, но с тех пор боитесь тесных пространств и цените каждый вдох.",
        "attr_mods": {"willpower": 1, "endurance": 1},
        "skill_mods": {"survival": 2, "engineering": 1},
    },
    {
        "id": "FY_ELITE_BOARDING_SCHOOL", "name": "Элитная школа-интернат",
        "group": "Академические",
        "description": "Лучшие репетиторы, костюмы от Мицубиси-Армани и однокурсники из семей членов Совета ООН. Связи на всю жизнь — и пара скелетов в шкафу.",
        "attr_mods": {"charisma": 1, "intelligence": 1},
        "skill_mods": {"diplomacy": 1, "education": 1},
    },
    {
        "id": "FY_PIRATE_CAPTIVE", "name": "Пленник космических пиратов",
        "group": "Криминальные",
        "description": "Полгода в плену у пиратов-утилизаторов. Научились их языку, повадкам и в итоге сбежали, прихватив их карты маршрутов.",
        "attr_mods": {"reflexes": 1},
        "skill_mods": {"stealth": 1, "survival": 1, "criminal": 1},
    },
    {
        "id": "FY_MILITARY_BRAT", "name": "Ребёнок военной базы",
        "group": "Военные",
        "description": "Росли среди казарм, плацев и оружейных складов. К 12 годам разбирали и собирали автомат вслепую. Дисциплина в крови.",
        "attr_mods": {"endurance": 1},
        "skill_mods": {"combat": 1, "survival": 1, "stealth": 1},
    },
    {
        "id": "FY_MEDIA_SENSATION", "name": "Медийная сенсация",
        "group": "Социальные",
        "description": "В 15 лет случайно записали на видео коррупцию чиновника. Стали героями сети на неделю — а потом целью для тех, кого разоблачили.",
        "attr_mods": {"charisma": 1},
        "skill_mods": {"negotiation": 1, "stealth": 1, "criminal": 1},
    },
    {
        "id": "FY_LAB_SUBJECT", "name": "Подопытный в лаборатории",
        "group": "Медицинские",
        "description": "«Добровольное» участие в экспериментах корпорации Протоген. Инъекции, тесты, мониторинг 24/7. Сбежали, но кое-что в организме изменилось навсегда.",
        "attr_mods": {"endurance": 1, "willpower": 1},
        "skill_mods": {"medicine": 1, "biology": 1},
    },
    {
        "id": "FY_STATION_MECHANIC", "name": "Механик орбитальной станции",
        "group": "Технологические",
        "description": "С 13 лет помогали отцу чинить системы жизнеобеспечения на станции Тихо. Знаете каждый клапан и каждую трубу — и цену ошибки при ремонте.",
        "attr_mods": {"dexterity": 1},
        "skill_mods": {"engineering": 2, "technology": 1},
    },
]


SPECIALIZATIONS = [
    # ═══ ТЕХНИЧЕСКИЕ ═══
    {
        "id": "SPEC_HACKER", "name": "Хакер",
        "group": "Технические",
        "description": "Мастер цифрового мира. Взламываете сети, обходите защиту и крадёте данные — ваш мозг и нейроинтерфейс опаснее любого оружия.",
        "skill_mods": {"hacking": 3, "technology": 2},
        "equipment": ["Портативный хакерский комплект", "Зашифрованный коммлинк", "Нейроинтерфейс"],
    },
    {
        "id": "SPEC_ENGINEER", "name": "Инженер",
        "group": "Технические",
        "description": "Техсистемы и ремонт — ваша стихия. Можете починить реактор скотчем и проволокой, а собрать дрона — с закрытыми глазами.",
        "skill_mods": {"engineering": 3, "technology": 2},
        "equipment": ["Инженерный набор", "Диагностический сканер", "Ремкомплект"],
    },
    {
        "id": "SPEC_SCIENTIST", "name": "Учёный",
        "group": "Технические",
        "description": "Исследователь и аналитик. Вы видите закономерности там, где другие видят хаос. Данные — ваше оружие.",
        "skill_mods": {"education": 2, "biology": 2, "technology": 1},
        "equipment": ["Лабораторный набор", "Анализатор данных", "Научный журнал"],
    },
    {
        "id": "SPEC_QUANTUM_HACKER", "name": "Квантовый хакер",
        "group": "Технические",
        "description": "Специалист по квантовым компьютерам и криптографии нового поколения. Обычные хакеры ломают пароли — вы ломаете реальность.",
        "skill_mods": {"hacking": 3, "technology": 1, "education": 1},
        "equipment": ["Квантовый компьютер", "Шифровальные ключи", "Нейроинтерфейс v2"],
    },
    # ═══ БОЕВЫЕ ═══
    {
        "id": "SPEC_SOLDIER", "name": "Солдат",
        "group": "Боевые",
        "description": "Военный боец, обученный убивать. Огнестрельное оружие, тактика, выживание на поле боя — ваш хлеб.",
        "skill_mods": {"combat": 3, "survival": 1, "piloting": 1},
        "equipment": ["Штурмовая винтовка", "Бронежилет", "Медкит"],
    },
    {
        "id": "SPEC_ASSASSIN", "name": "Корпоративный убийца",
        "group": "Боевые",
        "description": "Профессиональный киллер на службе мегакорпораций. Тихо, чисто, без следов — ваш фирменный стиль.",
        "skill_mods": {"combat": 2, "stealth": 3},
        "equipment": ["Бесшумное оружие", "Корпоративные документы", "Набор ядов"],
    },
    {
        "id": "SPEC_BOUNTY_HUNTER", "name": "Охотник за головами",
        "group": "Боевые",
        "description": "Цель объявлена — цель будет найдена. Вы выслеживаете беглецов по всей системе за хорошую награду.",
        "skill_mods": {"combat": 2, "stealth": 1, "piloting": 1, "criminal": 1},
        "equipment": ["Плазменный пистолет", "Трекер-маяк", "Наручники", "Бронежилет"],
    },
    # ═══ СОЦИАЛЬНЫЕ ═══
    {
        "id": "SPEC_NEGOTIATOR", "name": "Переговорщик",
        "group": "Социальные",
        "description": "Дипломат и медиатор. Ваши слова — оружие мощнее любого бластера. Вы можете убедить врага стать другом.",
        "skill_mods": {"negotiation": 3, "diplomacy": 2},
        "equipment": ["Дипимунитет", "Переводчик", "Элитный костюм"],
    },
    {
        "id": "SPEC_TRADER", "name": "Торговец",
        "group": "Социальные",
        "description": "Коммерция и сети. Знаете цену каждому товару от Земли до Плутона. Связи — ваш главный капитал.",
        "skill_mods": {"negotiation": 2, "bureaucracy": 1, "diplomacy": 1, "piloting": 1},
        "equipment": ["Торговая лицензия", "Кредитная карта VIP", "Каталог товаров"],
    },
    {
        "id": "SPEC_ARTIST", "name": "Артист",
        "group": "Социальные",
        "description": "Влияние и сцена. Музыкант, актёр или визуальный художник — ваше искусство открывает любые двери.",
        "skill_mods": {"diplomacy": 2, "negotiation": 2, "education": 1},
        "equipment": ["Сценический костюм", "Аудио-система", "Фан-база"],
    },
    {
        "id": "SPEC_FIXER", "name": "Фиксер",
        "group": "Социальные",
        "description": "Посредник теневого мира. Вы знаете всех и всё, и за правильную цену можете организовать что угодно.",
        "skill_mods": {"negotiation": 2, "criminal": 2, "stealth": 1},
        "equipment": ["Зашифрованный телефон", "Сеть контактов", "Поддельные документы"],
    },
    # ═══ ПИЛОТЫ ═══
    {
        "id": "SPEC_PILOT", "name": "Пилот",
        "group": "Пилоты",
        "description": "Ас пилотирования. От шахтёрских баржей до истребителей — вы можете управлять чем угодно.",
        "skill_mods": {"piloting": 3, "engineering": 1, "survival": 1},
        "equipment": ["Доступ к личному кораблю", "Навигационный компьютер", "Лётная куртка"],
    },
    {
        "id": "SPEC_SMUGGLER", "name": "Контрабандист",
        "group": "Пилоты",
        "description": "Быстрый корабль, тайные маршруты и холодные нервы. Вы доставите что угодно куда угодно — без вопросов.",
        "skill_mods": {"piloting": 2, "criminal": 2, "stealth": 1},
        "equipment": ["Быстрый корабль с тайником", "Сканер патрулей", "Фальшивые накладные"],
    },
    # ═══ МЕДИЦИНСКИЕ ═══
    {
        "id": "SPEC_MEDIC", "name": "Медик",
        "group": "Медицинские",
        "description": "Специалист по медицине. От полевой хирургии до кибернетических имплантов — вы спасаете жизни.",
        "skill_mods": {"medicine": 3, "biology": 1, "technology": 1},
        "equipment": ["Медицинский сканер", "Хирургический набор", "Стимпаки x5"],
    },
    {
        "id": "SPEC_GENE_SCULPTOR", "name": "Генный скульптор",
        "group": "Медицинские",
        "description": "Мастер генетических модификаций и биологического дизайна. Создаёте жизнь по чертежам.",
        "skill_mods": {"biology": 3, "medicine": 2},
        "equipment": ["Генетический сканер", "Био-лаборатория", "Образцы генов"],
    },
    # ═══ РАЗВЕДКА ═══
    {
        "id": "SPEC_SPY", "name": "Шпион",
        "group": "Разведка",
        "description": "Скрытность и информация. Двойная жизнь — ваша норма. Никто не знает вашего настоящего имени.",
        "skill_mods": {"stealth": 3, "hacking": 1, "diplomacy": 1},
        "equipment": ["Камуфляж", "Жучки-прослушки", "Поддельные документы"],
    },
    {
        "id": "SPEC_INVESTIGATOR", "name": "Детектив",
        "group": "Разведка",
        "description": "Частный сыщик космической эры. Находите людей, раскрываете заговоры и копаете до истины.",
        "skill_mods": {"education": 2, "stealth": 1, "hacking": 1, "negotiation": 1},
        "equipment": ["Детективный набор", "Базы данных", "Замаскированная камера"],
    },
    {
        "id": "SPEC_VOID_PRIEST", "name": "Жрец Пустоты",
        "group": "Уникальные",
        "description": "Духовный лидер космических культов и мистических сект. Ваша вера — в бездну между звёзд.",
        "skill_mods": {"diplomacy": 2, "education": 1, "medicine": 1, "negotiation": 1},
        "equipment": ["Религиозные артефакты", "Ритуальные одеяния", "Медитативные препараты"],
    },
    {
        "id": "SPEC_MEMORY_THIEF", "name": "Похититель воспоминаний",
        "group": "Уникальные",
        "description": "Эксперт по извлечению и изменению человеческих воспоминаний. Вы крадёте не вещи — вы крадёте саму суть людей.",
        "skill_mods": {"hacking": 2, "medicine": 1, "stealth": 1, "technology": 1},
        "equipment": ["Экстрактор памяти", "Нейро-препараты", "Мозговой сканер"],
    },
]
